--- 
abstract: PITA Guest Driver for Qemu images
author: Adam Kennedy, L<http://ali.as/>, cpan@ali.as
build_requires: 
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: PITA-Guest-Driver-Qemu
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  File::Remove: 0.34
  File::Temp: 0.15
  File::Which: 0.05
  Filesys::MakeISO: 0
  Filesys::MakeISO::Driver::Mkisofs: 0
  PITA: 0.40
  Params::Util: 0.10
  perl: 5.005
version: 0.40
